#!/bin/sh


source $HOME/.config/X11/xprofile

# DWM

#while true; do 
#    dwm >dev/null 2>&1
#done

#exec ~/.config/chadwm/scripts/./autostart
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &

exec dwm
