#!/bin/sh
# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# Speedy keys
xset r rate 210 40

# Keyboard
setxkbmap br # Keyboard
setxkbmap -option caps:escape # Keyboard

nitrogen --restore

# Colors
xrdb $HOME/.dotfiles/X11/.config/X11/Xresources

# Initialization program
autostart="mpd xbanish dunst flameshot dwmblocks xcompmgr"
#autostart="dunst dwmblocks "
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

