import = [
    "~/.config/alacritty/gruvbox_dark.toml",
]

[env]
TERM="xterm-256color"

[font]
size = 10.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 30
y = 30

[shell]
program = "/usr/bin/zsh"

[terminal]
osc52 = "Disabled"
