sudo bash -c '                                                                                                                                                                                                                         
     umask 077                                                                                                                                                                                                                              
     IFS= read -rsp "LUKS passphrase: " first </dev/tty                                                                                                                                                                                     
     printf "\n"                                                                                                                                                                                                                            
     IFS= read -rsp "Confirm passphrase: " second </dev/tty                                                                                                                                                                                 
     printf "\n"                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
     [ -n "$first" ] || {                                                                                                                                                                                                                   
       printf "Passphrase cannot be empty\n"                                                                                                                                                                                                
       exit 1                                                                                                                                                                                                                               
     }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
     [ "$first" = "$second" ] || {                                                                                                                                                                                                          
       printf "Passphrases do not match\n"                                                                                                                                                                                                  
       exit 1                                                                                                                                                                                                                               
     }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
     printf "%s" "$first" \                                                                                                                                                                                                                 
       > /var/lib/night-crawler-secrets/disko-password                                                                                                                                                                                      
     '
