#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin/statusbar":$PATH
export PATH="$HOME/.local/bin/":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH="$PATH:./node_modules/.bin"
export PATH="$BINPATH:/$PATH"
export PATH="$PATH:/home/ruan/.local/share/coursier/bin"

export SSLKEYLOGFILE=~/.config/ssl-key.log

XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.local/cache"
XDG_CONFIG_HOME="$HOME/.config"

# Clean up
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NVM_DIR="$XDG_DATA_HOME"/nvm
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo

alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'

. "$CARGO_HOME/env"
