#!/bin/sh
alias v='nvim'
alias g='lazygit'
alias z='zathura'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias cfnv='nvim ~/.dotfiles/nvim/.config/nvim/'
alias cfi3='nvim ~/.dotfiles/i3-old/.config/i3/config'
alias cfzsh='nvim ~/.dotfiles/zsh/.config/zsh/'
alias cfal='nvim ~/.dotfiles/alacritty/.config/alacritty/alacritty.yml'
alias cfpc='nvim ~/.dotfiles/picom/.config/picom/picom.conf'
alias cfza='nvim ~/.dotfiles/zathura/.config/zathura/zathurarc'
alias cfx='nvim ~/.dotfiles/X/.xprofile'
alias cfpo='nvim ~/.dotfiles/polybar/.config/polybar'
alias cfki='nvim ~/.dotfiles/kitty/.config/kitty'


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias m="git checkout master"
alias s="git checkout stable"

alias ls='ls --color=auto'

