# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") 
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e4f9d4c-87e3-41de-a3a6-3524461c5be0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3AD1-3059";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/29b83660-4925-4060-a0e6-ae4a4d6f24f1"; }
    ];

  # Harddrives
  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/23191058-4a9f-46a0-9d42-bb2e45abec59";
      fsType = "ext4";
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
	cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	graphics = {
		enable = true;
	        extraPackages = with pkgs; [
			intel-media-driver # For Kaby Lake (Gen7) and newer
			intel-compute-runtime # OpenCL
			libva-vdpau-driver
			libvdpau-va-gl
    		];
        };
  };
}
