#!/bin/sh

alias v='nvim'
alias g='lazygit'
alias z='zathura'
alias cfnv='nvim ~/.dotfiles/nvim/.config/nvim/'
alias cfi3='nvim ~/.dotfiles/i3/.config/i3/config'
alias cfzsh='nvim ~/.dotfiles/zsh/.config/zsh/'
alias cfal='nvim ~/.dotfiles/alacritty/.config/alacritty/alacritty.yml'
alias cfpc='nvim ~/.dotfiles/picom/.config/picom/picom.conf'
alias cfza='nvim ~/.dotfiles/zathura/.config/zathura/zathurarc'
alias cfx='nvim ~/.dotfiles/X11/.config/X11'
alias cfpo='nvim ~/.dotfiles/polybar/.config/polybar'
alias cfki='nvim ~/.dotfiles/kitty/.config/kitty'
alias cfki='nvim ~/.dotfiles/bin/.local/bin'


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias m="git checkout master"
alias s="git checkout stable"

alias l="exa --icons"
