import = [
    "~/.config/alacritty/gruvbox_dark.toml",
]

[env]
TERM="xterm-256color"

[font]
size = 10.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1.0

[window.padding]
x = 10
y = 10

[shell]
program = "/usr/bin/bash"

[terminal]
osc52 = "Disabled"
